apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
  {{- include "chart.labels" . | nindent 4 }}

  {{- with .Values.controllerManager.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.controllerManager.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  {{- if .Values.controllerManager.replicaCount }}
  replicas: {{ .Values.controllerManager.replicaCount }}
  {{- end }}
  {{- if .Values.controllerManager.strategy.type }}
  strategy:
    type: {{ .Values.controllerManager.strategy.type }}
  {{- end }}

  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
    
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: ScheduleAnyway

      containers:
        {{- if .Values.controllerManager.arguments }}
      - args:
        {{- range $key, $value := .Values.controllerManager.arguments }}
        {{- if $value }}
        - --{{ $key }}={{ $value }}
        {{- else }}
        - --{{ $key  }}
        {{- end }}
        {{- end }}
        {{- end }}
        
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.controllerManager.environment.KUBERNETES_CLUSTER_DOMAIN |quote}}
        - name: ENABLE_WEBHOOKS
          value: {{ .Values.controllerManager.environment.ENABLE_WEBHOOKS |quote }}
        - name: ENABLE_DEBUG
          value: {{ .Values.controllerManager.environment.ENABLE_DEBUG |quote }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        name: manager

        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP

        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10 }}

        {{- with .Values.controllerManager.manager.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}


        {{- with .Values.controllerManager.manager.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext: 
        {{- toYaml  .Values.controllerManager.containerSecurityContext | nindent 10 }}

        volumeMounts:
         {{- if .Values.controllerManager.enabledWebHooks  }}
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        {{- end }}  
        {{- if .Values.controllerManager.enabledCaCerts  }}
        - mountPath: /etc/ssl/certs/ca-certificates.crt
          name: ca-certificates
          subPath: ca-certificates.crt
          readOnly: true
        {{- end }}  

      terminationGracePeriodSeconds: 30 

      securityContext:
        {{- toYaml  .Values.controllerManager.podSecurityContext | nindent 10 }}
      serviceAccountName: {{ .Values.controllerManager.rbac.serviceAccountName }}
      volumes:
      {{- if .Values.controllerManager.enabledWebHooks  }}
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
      {{- end }}  
      
      {{- if .Values.controllerManager.enabledCaCerts  }}
      - name: ca-certificates
        secret:
          defaultMode: 420
          secretName: {{ .Values.controllerManager.caCertsSecretName| default "ca-certificates" }} 
      {{- end }}  


      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}