apiVersion: v1
kind: Secret
metadata:
  name: cview-issuer-credentials     # Secret name 
  namespace: cview-issuer            # namespace of cview-issuer operator
type: Opaque
stringData:
  authMethod: basic      # Allowed values :
                         #   basic (use with C-View version 7.1.0 and C-View Issuer version 0.0.35 or lower ) 
                         #   token (default - use with for C-View version 7.2.0 and C-View Issuer version 0.0.36 or lower upper) 
data:
  password: bXlQASDzd29yZA==          # user password as encoded base64 string (this is an example)
  username: ZG9tAQAluXHVzZXI=         # domain\user as encoded as base64 string (this is an example)
  
  # The token parameter is not avilabile yet 
  token: NnpOalMhWHJAQ.CFENURmc2ZzZmYwWjMvZUhLODVJY2hFbjVGUmN6QUEv  # request the API token from CView Administrator and encode it as base64 string (this is an example)
